const SET_POKEMONS = 'SET_POKEMONS';
const SET_LOADING = 'SET_LOADING';
const SET_FAVORITE = 'SET_FAVORITE';
const SET_SEARCH = 'SET_SEARCH';

export { SET_POKEMONS, SET_LOADING, SET_FAVORITE, SET_SEARCH };